image: 'registry.gitlab.com/pantomath-io/demo-tools:latest'

cache:
  paths:
    #- /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/michael.golfi/appinsights
  CC: clang-5.0


stages:
  - build
  - test
  - deploy

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

Build:
  artifacts:
    expire_in: 1 hour
    paths:
      - vendor/*
      - $CI_PROJECT_NAME
    untracked: true
  script:
    - make install
    # Check if it compiles without errors
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo --ldflags="-s" -o $CI_PROJECT_NAME
  stage: build

Lint:
  stage: test
  # Syntax warnings come out as errors
  allow_failure: true
  script:
    - make lint

Test:
  stage: test
  script:
    - make test

Race:
  stage: test
  script:
    - make race

Memory Sanitize:
  stage: test
  script:
    - make msan

Coverage:
  stage: test
  script:
    - make coverage

Deploy:
  image: 'docker:latest'
  stage: deploy
  script:
    - docker build -t rootfsimage .
    - id=$(docker create rootfsimage true)
    - mkdir -p plugin/rootfs
    - docker export "$id" | tar -x -C plugin/rootfs
    - cp config.json ./plugin/

    - docker login -u $USERNAME -p $PASSWORD

    - docker plugin create michaelgolfi/appinsights:${CI_BUILD_REF:0:5} ./plugin
    - docker plugin create michaelgolfi/appinsights:latest ./plugin
    - docker plugin push michaelgolfi/appinsights:${CI_BUILD_REF:0:5}
    - docker plugin push michaelgolfi/appinsights:latest
  services:
    - 'docker:dind'
  except:
    - tags

Deploy Tag:
  image: 'docker:latest'
  stage: deploy
  script:
    - docker build -t rootfsimage .
    - id=$(docker create rootfsimage true)
    - mkdir -p plugin/rootfs
    - docker export "$id" | tar -x -C plugin/rootfs
    - cp config.json ./plugin/

    - docker login -u $USERNAME -p $PASSWORD

    - docker plugin create michaelgolfi/appinsights:$CI_COMMIT_TAG ./plugin
    - docker plugin create michaelgolfi/appinsights:latest ./plugin
    - docker plugin push michaelgolfi/appinsights:$CI_COMMIT_TAG
    - docker plugin push michaelgolfi/appinsights:latest
  services:
    - 'docker:dind'
  only:
    - tags  